### PR TITLE
fix secman path in env variables

### PR DESCRIPTION
**Pull request by Timothee-Cardoso**
add this command

```powershell
[System.Environment]::SetEnvironmentVariable("Path", $Env:Path + ";$loc\bin", [System.EnvironmentVariableTarget]::User)
```

### CODE REVIEW

**Review by abdfnx — APPROVED** [review]
ok, I'll try it

**Comment by abdfnx** [comment]
good code @Timothee-Cardoso , you fix the error

**Comment by abdfnx** [comment]
but there's a weird thing


 
it's write the path twice

what's wrong ?

**Comment by Timothee-Cardoso** [comment]
it's weird, I don't know what's the error, but I'll find out 👍

**Pull request merged**
